print("Goldren Fruit Shop")
print("--------------------")
print("apple      *1  10 $ ")
print("orange     *1   7 $ ")
print("mango      *3  30 $ ")
print("melon      *1  20 $ ")
print("peach      *3  24 $ ")
print("banana     *5  30 $ ")
print("durian     *1  25 $ ")
print("strawberry *2  14 $ ")
print("        Total 160 $")
print("--------------------")